<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FindPet.BusinessLogicLayer\FindPet.BusinessLogicLayer.csproj" />
    <ProjectReference Include="..\FindPet.Domain\FindPet.Domain.csproj" />
    <ProjectReference Include="..\FindPet.Infrastructure\FindPet.Infrastructure.csproj" />
  </ItemGroup>

</Project>
