name: 'Project Automation'

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, ready_for_review]

jobs:
  automate-project-issues:
    runs-on: ubuntu-latest
    steps:
      # Add new issues to project
      - name: Add new issue to project
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PROJECTS_PAT }}
          user: AndriiKhalin
          project_id: 6
          status_value: "To Do"
          resource_node_id: ${{ github.event.issue.node_id }}

      # Move issue to In Progress when PR is opened
      - name: Move issue to In Progress when PR is opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PROJECTS_PAT }}
          user: AndriiKhalin
          project_id: 6
          status_value: "In progress"
          resource_node_id: ${{ github.event.pull_request.node_id }}
          get_linked_issue: true

      # Move issue to In Review when PR is ready for review
      - name: Move issue to In Review
        if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PROJECTS_PAT }}
          user: AndriiKhalin
          project_id: 6
          status_value: "In review"
          resource_node_id: ${{ github.event.pull_request.node_id }}
          get_linked_issue: true

      # Move issue to Done when PR is merged
      - name: Move issue to Done when PR is merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PROJECTS_PAT }}
          user: AndriiKhalin
          project_id: 6
          status_value: "Done"
          resource_node_id: ${{ github.event.pull_request.node_id }}
          get_linked_issue: true
